# 数据源配置
spring:
  flyway:
    enabled: true
    locations: classpath:db/mysql
    baselineOnMigrate: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:63306}/${DB_NAME:demo_test}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: ${DB_USER:aaa}
      password: ${DB_PASSWD:bbb}