package com.kuafu.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * Single todo task generated by the AI helper.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AiTodoSuggestionTask {

    @JsonProperty("reminder_item_id")
    private Integer reminderItemId;

    @JsonProperty("category")
    private String category;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("due_time")
    private Date dueTime;

    @JsonProperty("priority")
    private String priority;
}