# 数据源配置
spring:
  flyway:
    enabled: true
    locations: classpath:db/sqlite
    baselineOnMigrate: true
    placeholder-replacement: false
    validate-on-migrate: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.sqlite.JDBC
    druid:
      url: jdbc:sqlite:${SQLITE_PATH:demo.sqlite}?journal_mode=WAL&busy_timeout=5000
      username:
      password:

